# Generated by Django 5.1.15 on 2026-04-25 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_internal', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('forecast_date', models.DateField(blank=True, null=True)),
                ('realized_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('realized_date', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='budget.category')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='budget.project')),
            ],
            options={
                'ordering': ['forecast_date', 'realized_date'],
            },
        ),
        migrations.CreateModel(
            name='WaterfallTranche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.SmallIntegerField()),
                ('rule_type', models.CharField(choices=[('RECOUPMENT', 'Recoupment'), ('RESIDUAL', 'Residual')], max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranches', to='budget.project')),
            ],
            options={
                'ordering': ['project', 'priority'],
                'unique_together': {('project', 'priority')},
            },
        ),
        migrations.CreateModel(
            name='LineParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('budget_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='budget.budgetline')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_participations', to='budget.partner')),
            ],
            options={
                'unique_together': {('budget_line', 'partner')},
            },
        ),
        migrations.CreateModel(
            name='ProjectParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_participations', to='budget.partner')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='budget.project')),
            ],
            options={
                'unique_together': {('project', 'partner')},
            },
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=256)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='budget.project')),
            ],
            options={
                'unique_together': {('project', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='TrancheClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recoup_target', models.CharField(blank=True, choices=[('FIXED', 'Fixed Amount'), ('EXPENSE_SUM', 'Sum of Expenses')], max_length=20, null=True)),
                ('recoup_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranche_claims', to='budget.partner')),
                ('tranche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='budget.waterfalltranche')),
            ],
            options={
                'unique_together': {('tranche', 'partner')},
            },
        ),
    ]
