# Generated by Django 5.1.15 on 2026-05-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_projecttag_ltree'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='partner',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
