# Generated by Django 5.1.15 on 2026-05-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_category_code_and_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='year',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
